# Generated by Django 3.0.3 on 2020-09-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('ins_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ins_initiator_id', models.CharField(max_length=10)),
                ('ins_name', models.CharField(max_length=255)),
                ('ins_pay', models.CharField(max_length=255)),
                ('ins_profit', models.CharField(max_length=255)),
                ('ins_picture', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('instype_id', models.IntegerField(primary_key=True, serialize=False)),
                ('instype_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'insurance_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('usertype_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('usertype_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_password', models.CharField(max_length=20)),
                ('user_gender', models.IntegerField(blank=True, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user_email', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('user_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.ForeignKey(db_column='user_type', on_delete=django.db.models.deletion.DO_NOTHING, to='model.UserType')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
