# Generated by Django 3.0.3 on 2020-09-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('post_time', models.DateTimeField()),
                ('post_name', models.CharField(max_length=255)),
                ('post_info', models.CharField(blank=True, max_length=255, null=True)),
                ('post_looked', models.IntegerField(blank=True, null=True)),
                ('post_lmsg', models.CharField(blank=True, max_length=255, null=True)),
                ('post_type', models.CharField(max_length=50)),
                ('post_picurl', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('post_type_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('post_type_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'post_type',
                'managed': False,
            },
        ),
    ]
