# Generated by Django 3.0.7 on 2020-10-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_post_posttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurance',
            options={'managed': False, 'verbose_name_plural': '保险表'},
        ),
        migrations.AlterModelOptions(
            name='insurancetype',
            options={'managed': False, 'verbose_name_plural': '保险类型表'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False, 'verbose_name_plural': '帖子表'},
        ),
        migrations.AlterModelOptions(
            name='posttype',
            options={'managed': False, 'verbose_name_plural': '帖子类型表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name_plural': '用户类型表'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.IntegerField(blank=True, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='电话'),
        ),
    ]
