# Generated by Django 3.0.7 on 2020-10-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20201007_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceSubtype',
            fields=[
                ('ins_subtype_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ins_subtype_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '保险sub',
                'db_table': 'insurance_subtype',
                'managed': False,
            },
        ),
    ]
